
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DECIMAL DIV ENTERO MULT PAREN_DER PAREN_IZQ RESTA SUMAS : EE : E SUMA TE : E RESTA TE : TT : T MULT FT : T DIV FT : FF : PAREN_IZQ E PAREN_DERF : NN : DECIMALN : ENTERO'
    
_lr_action_items = {'PAREN_IZQ':([0,5,9,10,11,12,],[5,5,5,5,5,5,]),'DECIMAL':([0,5,9,10,11,12,],[7,7,7,7,7,7,]),'ENTERO':([0,5,9,10,11,12,],[8,8,8,8,8,8,]),'$end':([1,2,3,4,6,7,8,14,15,16,17,18,],[0,-1,-4,-7,-9,-10,-11,-2,-3,-5,-6,-8,]),'SUMA':([2,3,4,6,7,8,13,14,15,16,17,18,],[9,-4,-7,-9,-10,-11,9,-2,-3,-5,-6,-8,]),'RESTA':([2,3,4,6,7,8,13,14,15,16,17,18,],[10,-4,-7,-9,-10,-11,10,-2,-3,-5,-6,-8,]),'PAREN_DER':([3,4,6,7,8,13,14,15,16,17,18,],[-4,-7,-9,-10,-11,18,-2,-3,-5,-6,-8,]),'MULT':([3,4,6,7,8,14,15,16,17,18,],[11,-7,-9,-10,-11,11,11,-5,-6,-8,]),'DIV':([3,4,6,7,8,14,15,16,17,18,],[12,-7,-9,-10,-11,12,12,-5,-6,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'S':([0,],[1,]),'E':([0,5,],[2,13,]),'T':([0,5,9,10,],[3,3,14,15,]),'F':([0,5,9,10,11,12,],[4,4,4,4,16,17,]),'N':([0,5,9,10,11,12,],[6,6,6,6,6,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('S -> E','S',1,'p_S','grammar.py',49),
  ('E -> E SUMA T','E',3,'p_E_plus','grammar.py',53),
  ('E -> E RESTA T','E',3,'p_E_minus','grammar.py',57),
  ('E -> T','E',1,'p_E_term','grammar.py',61),
  ('T -> T MULT F','T',3,'p_T_mul','grammar.py',65),
  ('T -> T DIV F','T',3,'p_T_div','grammar.py',69),
  ('T -> F','T',1,'p_T_factor','grammar.py',73),
  ('F -> PAREN_IZQ E PAREN_DER','F',3,'p_F_group','grammar.py',77),
  ('F -> N','F',1,'p_F_number','grammar.py',81),
  ('N -> DECIMAL','N',1,'p_N_decimal','grammar.py',85),
  ('N -> ENTERO','N',1,'p_N_integer','grammar.py',89),
]
